---
# yaml-language-server: $schema=https://schemas.rzegocki.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: romm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: romm-secret
    template:
      data:
        IGDB_CLIENT_ID: "{{ .IGDB_CLIENT_ID }}"
        IGDB_CLIENT_SECRET: "{{ .IGDB_CLIENT_SECRET }}"
        ROMM_AUTH_SECRET_KEY: "{{ .ROMM_AUTH_SECRET_KEY }}"
        SCREENSCRAPER_USER: "{{ .SCREENSCRAPER_USER }}"
        SCREENSCRAPER_PASSWORD: "{{ .SCREENSCRAPER_PASSWORD }}"
        STEAMGRIDDB_API_KEY: "{{ .STEAMGRIDDB_API_KEY }}"
  dataFrom:
    - extract:
        key: kubernetes/media/romm
