---
# yaml-language-server: $schema=https://schemas.rzegocki.dev/other/app-template-hr.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: romm
spec:
  chartRef:
    kind: OCIRepository
    name: romm
  interval: 1h
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
          glance/name: RomM
          glance/icon: di:romm
          glance/url: https://romm.${ROOT_DOMAIN}
        containers:
          app:
            image:
              repository: ghcr.io/rommapp/romm
              tag: 5.3.0@sha256:dc586cb3a2c7316fcffb3dc273171b1964523f0f409e989295d26d2199df1d4e
            env:
              # DISABLE_USERPASS_LOGIN: "true"
              DB_NAME: romm
              DB_PORT: 5432
              ENABLE_RESCAN_ON_FILESYSTEM_CHANGE: "true"
              ENABLE_SCHEDULED_CONVERT_IMAGES_TO_WEBP: "true"
              ENABLE_SCHEDULED_RESCAN: "true"
              ENABLE_SCHEDULED_UPDATE_LAUNCHBOX_METADATA: "true"
              HASHEOUS_API_ENABLED: "true"
              HLTB_API_ENABLED: "true"
              IPV4_ONLY: "true"
              LAUNCHBOX_API_ENABLED: "true"
              OIDC_ALLOW_REGISTRATION: "true"
              OIDC_AUTOLOGIN: "true"
              OIDC_ENABLED: "true"
              OIDC_PROVIDER: "pocketid"
              OIDC_REDIRECT_URI: https://romm.${ROOT_DOMAIN}/api/oauth/openid
              OIDC_SERVER_APPLICATION_URL: https://id.${ROOT_DOMAIN}
              OIDC_TLS_CACERTFILE: /etc/ssl/certs/ca-certificates.crt
              PLAYMATCH_API_ENABLED: "true"
              REDIS_HOST: romm-dragonfly
              REDIS_PORT: 6379
              RESCAN_ON_FILESYSTEM_CHANGE_DELAY: 5
              ROMM_BASE_PATH: /romm
              ROMM_BASE_URL: https://romm.${ROOT_DOMAIN}
              ROMM_DB_DRIVER: postgresql
              ROMM_PORT: &port 80
              SCHEDULED_RESCAN_CRON: "0 3 * * *"
              TZ: Europe/Warsaw
              DB_HOST:
                secretKeyRef:
                  name: media-db-app
                  key: host
              DB_PASSWD:
                secretKeyRef:
                  name: media-db-app
                  key: password
              DB_USER:
                secretKeyRef:
                  name: media-db-app
                  key: username
            envFrom:
              - secretRef:
                  name: "romm-secret"
              - secretRef:
                  name: "romm-oidc-credentials"
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/heartbeat
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 4Gi
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      labels:
        egress.cilium.io/auth: "true"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        ports:
          http:
            appProtocol: kubernetes.io/ws
            port: *port
    route:
      app:
        hostnames:
          - "romm.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - kind: Service
                name: romm
                port: 80
            matches:
              - path:
                  type: PathPrefix
                  value: /
            filters:
              - type: ResponseHeaderModifier
                responseHeaderModifier:
                  set:
                    - name: Content-Security-Policy
                      value: >-
                        default-src 'self' data: blob:;
                        img-src 'self' data: blob: https:;
                        object-src 'none';
                        script-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob:;
                        style-src 'self' 'unsafe-inline';
    persistence:
      configfile:
        type: configMap
        name: romm-configmap
        advancedMounts:
          main:
            app:
              - subPath: config.yaml
                path: /romm/config/config.yml
      media:
        type: custom
        volumeSpec:
          csi:
            driver: nfs.csi.k8s.io
            volumeAttributes:
              server: nas.internal
              share: "/mnt/tank/retro/romm"
              mountOptions: "noac,nfsvers=4.1,nconnect=16,hard,noatime"
        advancedMounts:
          main:
            app:
              - path: /romm/assets
                subPath: assets
              - path: /romm/cache
                subPath: cache
              - path: /romm/library
                subPath: library
              - path: /romm/resources
                subPath: resources
      homelab-root-ca:
        type: configMap
        name: homelab-root-ca
        advancedMounts:
          main:
            app:
              - path: /etc/ssl/certs/ca-certificates.crt
                subPath: ca.crt
                readOnly: true
      tmp:
        type: emptyDir
        advancedMounts:
          main:
            app:
              - path: /etc/nginx/conf.d
                subPath: nginx
              - path: /home/romm
                subPath: home
              - path: /romm/config
                subPath: config
              - path: /tmp
                subPath: tmp
