---
# yaml-language-server: $schema=https://schemas.ajgon.casa/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: retrom
spec:
  name: retrom
  owner: app
  cluster:
    name: retro-db
