---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/secretstore_v1.json
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: retro-db
spec:
  provider:
    kubernetes:
      remoteNamespace: retro
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: retro-db
---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: retrom
spec:
  secretStoreRef:
    kind: SecretStore
    name: retro-db
  target:
    name: retrom-secret
    template:
      data:
        config.json: |
          {
            "connection": {
              "port": 5101,
              "dbUrl": "{{ regexReplaceAll "/app$" (index . "fqdn-uri") "/retrom" }}"
            },
            "contentDirectories": [
              { "path": "/roms/", "storageType": "MultiFileGame" }
            ],
            "igdb": {
              "clientId": "{{ .RETRO_IGDB_CLIENT_ID }}",
              "clientSecret": "{{ .RETRO_IGDB_CLIENT_SECRET }}"
            }
          }

  dataFrom:
    - extract:
        key: retro-db-app
    - extract:
        key: retro-db-store-secret
