---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
components:
  - ../../../../components/namespace
resources:
  - ./_namespace.yaml
  - ./bifrost.yaml
  - ./hermes-agent.yaml
  - ./open-webui.yaml
  - ./openedai-speech.yaml
  - ./whisper.yaml
