---
# yaml-language-server: $schema=https://schemas.rzegocki.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: geopulse
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: geopulse-secret
    template:
      data:
        ai-encryption-key.txt: "{{ .AI_ENCRYPTION_KEY }}"
        jwt-private-key.pem: "{{ .JWT_PRIVATE_KEY }}"
        jwt-public-key.pem: "{{ .JWT_PUBLIC_KEY }}"
  dataFrom:
    - extract:
        key: kubernetes/default/geopulse
