---
# yaml-language-server: $schema=https://schemas.ajgon.casa/other/docker-compose.json
services:
  borgmatic:
    image: ghcr.io/borgmatic-collective/borgmatic:2.1.3@sha256:e37e3398dee161e6d011b949c5923cf6e5a405e60397acc5bc512031f3b5a096
    container_name: borgmatic
    restart: always
    env_file:
      - ./compose.env
      - ./override.env
    configs:
      - source: homelab
        target: /etc/borgmatic.d/homelab.yaml
      - source: legacy
        target: /etc/borgmatic.d/legacy.yaml
      - source: nas
        target: /etc/borgmatic.d/nas.yaml
    volumes:
      - /mnt/cache:/mnt/cache:ro
      - /mnt/tank:/mnt/tank:ro
      - "${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}/volumes/borgmatic/config:/config"

configs:
  homelab:
    file: ./config/homelab.yaml
  legacy:
    file: ./config/legacy.yaml
  nas:
    file: ./config/nas.yaml
