---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wakapi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: wakapi-secret
    template:
      data:
        WAKAPI_PASSWORD_SALT: "{{ .WAKAPI_PASSWORD_SALT }}"
        WAKA_API_KEY: "{{ .WAKAPI_API_KEY }}"
  dataFrom:
    - extract:
        key: kubernetes/default/wakapi
