---
# yaml-language-server: $schema=https://schemas.ajgon.casa/custom/sops.config.json
#
# To get a new key from remote SSH machine, invoke:
# nix-shell -p ssh-to-age --run 'cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age'

keys:
  - users:
      - &ajgon ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOrBLT88ZZ+lO8hHcj+4jqtor79OLhQZcDWF98kkWkfn
  - hosts:
      - &meemee age1ls53g22c75czpfshaf5yvzn7zmdk4gp6ylgdca3r0rxl9era5d6s0slsda

creation_rules:
  - path_regex: docker/hosts/meemee/.*\.sops\.(env|toml)$
    key_groups:
      - age:
          - *ajgon
          - *meemee
  - path_regex: scripts/.*\.sops\.env$
    key_groups:
      - age:
          - *ajgon
