[project]
name = "nixlab"
revision = "1.0"

[profiles.default]
AWS_ACCESS_KEY_ID = { required = true }
AWS_SECRET_ACCESS_KEY = { required = true }
TOFU_TFVARS = { required = true }
VAULT_TOKEN = { required = true }
