[project]
name = "nixlab"
revision = "1.0"

[profiles.default]
ANSIBLE_USER_PASSWORD = { required = true, description = "Password for unprivileged user on provisioned machines" }
ANSIBLE_VAULT_PASSWORD = { required = true, description = "Password for ansible vault secrets" }
AWS_ACCESS_KEY_ID = { required = true, description = "Access key for attic S3 backend" }
AWS_SECRET_ACCESS_KEY = { required = true, description = "Secret key for attic S3 backend" }
TOFU_TFVARS = { required = true, description = "Configuration for opentofu" }
VAULT_TOKEN = { required = true, description = "Token to pull openbao secrets" }
