[global]
  e2dsa                   # enable file indexing and filesystem scanning
  e2ts                    # enable multimedia indexing

  ipa: lan                # allow LAN only; reject internet IPs
  xff-src: 172.30.0.0/16  # allow k8s pods as reverse proxy source
  df: 512m                # stop accepting uploads if less than 512M free disk space
  ver                     # show copyparty version in the controlpanel
  name: DeeDee            # change the server-name that's displayed in the browser

[/]
  /data
  accs:
    A: *
