---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: Lint everything
'on':
  workflow_dispatch:
  pull_request:
    branches:
      - "!renovate/*"
  push:
    branches:
      - "renovate/*"

concurrency:
  group: ${{ forgejo.ref }}-${{ forgejo.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  main:
    runs-on: docker
    environment: production
    container: ghcr.io/cachix/devenv/devenv:v2.1.2
    steps:
      - name: Checkout
        run: |
          git init -b master
          git remote add origin \
          "http://x-access-token:${FORGEJO_TOKEN}@${FORGEJO_SERVER_URL#http*://}/${FORGEJO_REPOSITORY}.git"
          git fetch --depth=1 origin "${FORGEJO_REF_NAME}"
          git checkout FETCH_HEAD
          sed -i'' 's@enable: true@enable: false@g' devenv.yaml

      - name: Run linters
        run: |
          devenv test -v
        env:
          YLS_RESOLVE_URLS: "1"
