---
# yaml-language-server: $schema=https://schemas.ajgon.casa/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate-operator
spec:
  chartRef:
    kind: OCIRepository
    name: renovate-operator
  interval: 30m
  values:
    deployment:
      annotations:
        glance/name: Renovate Operator
        glance/icon: di:renovate
        glance/url: https://renovate.${ROOT_DOMAIN}
      podLabels:
        egress.cilium.io/kube-apiserver: "true"
    fullnameOverride: renovate-operator
    route:
      enabled: true
      hostnames:
        - renovate.${ROOT_DOMAIN}
      parentRefs:
        - name: envoy-internal
          namespace: network
    webhook:
      enabled: true
