---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: vaultwarden-secret
    template:
      data:
        ADMIN_TOKEN: "{{ .VAULTWARDEN_ADMIN_TOKEN }}"
  dataFrom:
    - extract:
        key: kubernetes
