---
# yaml-language-server: $schema=https://schemas.ajgon.casa/other/app-template-hr.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
spec:
  chartRef:
    kind: OCIRepository
    name: vaultwarden
  interval: 1h
  values:
    controllers:
      main:
        annotations:
          glance/name: Vaultwarden
          glance/icon: di:vaultwarden-light
          glance/url: https://vaultwarden.${ROOT_DOMAIN}
        containers:
          app:
            image:
              repository: ghcr.io/dani-garcia/vaultwarden
              tag: 1.37.0@sha256:e6443e3d5ed8fcee2204b89ec778d7f24d0173bcc42d1ea34f990304f5f63f51
            env:
              DATA_FOLDER: /config
              DISABLE_ICON_DOWNLOAD: true
              DOMAIN: "https://vaultwarden.${ROOT_DOMAIN}"
              ICON_CACHE_TTL: 0
              INVITATIONS_ALLOWED: false
              PASSWORD_HINTS_ALLOWED: false
              ROCKET_LIMITS: "{json=104857600}"
              ROCKET_PORT: &port 80
              SHOW_PASSWORD_HINT: false
              SIGNUPS_ALLOWED: false
              SMTP_FROM: "deedee@${ROOT_DOMAIN}"
              SMTP_HOST: "smtp-relay.network.svc.cluster.local"
              SMTP_PORT: 25
              SMTP_SECURITY: "off"
              TZ: Europe/Warsaw
            envFrom:
              - secretRef:
                  name: "vaultwarden-secret"
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /alive
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 2Gi
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      labels:
        egress.cilium.io/smtp-relay: "true"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "vaultwarden.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: vaultwarden
                port: 80
            filters:
              - type: ResponseHeaderModifier
                responseHeaderModifier:
                  set:
                    - name: Content-Security-Policy
                      value: >-
                        default-src 'self';
                        object-src 'none';
                        script-src 'self' 'unsafe-inline' 'unsafe-eval';
                        style-src 'self' 'unsafe-inline';
    persistence:
      config:
        existingClaim: vaultwarden
