---
# yaml-language-server: $schema=https://schemas.ajgon.casa/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crypt
spec:
  components:
    - ../../../components/oidc
  interval: 1h
  patches:
    - patch: |-
        - op: replace
          path: /spec/targetRefs
          value:
            - group: gateway.networking.k8s.io
              kind: HTTPRoute
              name: crypt-base
            - group: gateway.networking.k8s.io
              kind: HTTPRoute
              name: crypt-ui
        - op: add
          path: /spec/oidc/cookieDomain
          value: crypt.${ROOT_DOMAIN}
      target:
        group: gateway.envoyproxy.io
        kind: SecurityPolicy
  path: ./kubernetes/apps/default/crypt
  postBuild:
    substitute:
      APP: crypt
      ROOT_DOMAIN: "${ROOT_DOMAIN}"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  wait: false
