---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../../../components/namespace
resources:
  - ./_namespace.yaml
  - ./_postgresql.yaml
  - ./atuin.yaml
  - ./bentopdf.yaml
  - ./chhoto-url.yaml
  - ./copyparty.yaml
  - ./crypt.yaml
  - ./davis.yaml
  - ./discord-bots.yaml
  - ./firefly.yaml
  - ./garmin.yaml
  - ./geopulse.yaml
  - ./glance.yaml
  - ./karakeep.yaml
  - ./kiwix.yaml
  - ./mail-archive.yaml
  - ./mindwtr.yaml
  - ./n8n.yaml
  - ./paperless-ngx.yaml
  - ./searxng.yaml
  - ./syncthing.yaml
  - ./wakapi.yaml
  - ./vaultwarden.yaml
