---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-ops-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: home-ops-runner-secret
    template:
      data:
        github_app_id: '{{ .HOME_OPS_RUNNER_GITHUB_APP_ID }}'
        github_app_installation_id: '{{ .HOME_OPS_RUNNER_GITHUB_APP_INSTALLATION_ID }}'
        github_app_private_key: '{{ .HOME_OPS_RUNNER_GITHUB_APP_PRIVATE_KEY }}'
  dataFrom:
    - extract:
        key: kubernetes/actions-runner-system/gha-runner-scale-set
---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ajgon-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: ajgon-runner-secret
    template:
      data:
        github_token: '{{ .AJGON_RUNNER_GITHUB_TOKEN }}'
  dataFrom:
    - extract:
        key: kubernetes/actions-runner-system/gha-runner-scale-set
