---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: beets-flask
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: beets-flask-secret
    template:
      data:
        client-id: "{{ .BEETS_CLIENT_ID }}"
        client-secret: "{{ .BEETS_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: kubernetes
