---
# yaml-language-server: $schema=https://schemas.ajgon.casa/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich
spec:
  name: immich
  owner: app
  cluster:
    name: immich-db
  extensions:
    - ensure: present
      name: cube
    - ensure: present
      name: earthdistance # requires: cube
    - ensure: present
      name: pg_trgm
    - ensure: present
      name: unaccent
    - ensure: present
      name: uuid-ossp
    - ensure: present
      name: vector
    - ensure: present
      name: vchord # requires: vector
