---
# yaml-language-server: $schema=https://schemas.ajgon.casa/other/app-template-hr.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  chartRef:
    kind: OCIRepository
    name: immich
  interval: 1h
  # Immich is a beast
  values:
    controllers:
      api:
        annotations:
          glance/name: Immich
          glance/icon: di:immich
          glance/url: https://immich.${ROOT_DOMAIN}
        pod:
          labels:
            egress.cilium.io/auth: "true"
        containers:
          app:
            image: &img
              repository: ghcr.io/immich-app/immich-server
              tag: v3.0.3@sha256:c716dc20f957aafd89fa9d284a2ec63e25c9e2d8d8e87c6197d540a3dce237db
            env: &env
              IMMICH_API_METRICS_PORT: &apiPort 8081
              IMMICH_CONFIG_FILE: /config/config.yaml
              IMMICH_ENV: &appEnv production
              IMMICH_HOST: "0.0.0.0"
              IMMICH_MACHINE_LEARNING_URL: "http://immich-machinelearning:3003"
              IMMICH_PORT: &port 80
              IMMICH_TELEMETRY_INCLUDE: "all" # enable metrics expose, not for calling home
              IMMICH_TRUSTED_PROXIES: "172.30.0.0/24"
              IMMICH_WORKERS_INCLUDE: "api"
              NODE_ENV: *appEnv
              NODE_EXTRA_CA_CERTS: /certs/homelab.pem
              REDIS_HOSTNAME: immich-dragonfly
              DB_DATABASE_NAME: &dbname "immich"
              DB_HOSTNAME: &dbhost
                secretKeyRef:
                  name: immich-db-app
                  key: host
              DB_PASSWORD: &dbpass
                secretKeyRef:
                  name: immich-db-app
                  key: password
              DB_USERNAME: &dbuser
                secretKeyRef:
                  name: immich-db-app
                  key: username
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/server/ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 10
              readiness: *probes
              startup: *probes
            securityContext: &sc
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
      microservices:
        pod:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/controller
                        operator: In
                        values:
                          - microservices
                  topologyKey: kubernetes.io/hostname
          resourceClaims:
            - name: gpu
              resourceClaimTemplateName: immich-gpu
        replicas: 3
        containers:
          app:
            image: *img
            env:
              <<: *env
              IMMICH_WORKERS_INCLUDE: "microservices"
              IMMICH_MICROSERVICES_METRICS_PORT: &msPort 8081
            probes:
              liveness: &msProbes
                enabled: true
                spec:
                  tcpSocket:
                    port: *msPort
              readiness: *msProbes
            resources: &resources
              claims:
                - name: gpu
            securityContext: *sc
      machinelearning:
        type: statefulset
        strategy: RollingUpdate
        replicas: 3
        pod:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/controller
                        operator: In
                        values:
                          - machinelearning
                  topologyKey: kubernetes.io/hostname
          dnsConfig:
            options:
              - name: ndots
                value: "1"
          resourceClaims:
            - name: gpu
              resourceClaimTemplateName: immich-gpu
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v3.0.3@sha256:d76fe88b69282c09a97eac4f82dafa82cfd77bce274bc742591cde974f87dacb
            env:
              MACHINE_LEARNING_HTTP_KEEPALIVE_TIMEOUT_S: "0" # https://github.com/immich-app/immich/discussions/12064
              TRANSFORMERS_CACHE: /cache
              HF_XET_CACHE: /cache/huggingface-xet
              MPLCONFIGDIR: /cache/matplotlib-config
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: &mlport 3003
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 10
              readiness: *probes
              startup: *probes
            resources: *resources
            securityContext: *sc
        statefulset:
          volumeClaimTemplates:
            - name: cache
              storageClass: ceph-block
              accessMode: ReadWriteOnce
              size: 10Gi
              advancedMounts:
                app:
                  - path: /cache
      album-creator:
        type: cronjob
        cronjob:
          schedule: "0 0 * * *" # every day
          successfulJobsHistory: 0
          failedJobsHistory: 5
          concurrencyPolicy: Forbid
        containers:
          app:
            image:
              repository: ghcr.io/salvoxia/immich-folder-album-creator
              tag: 1.0.0@sha256:0bfc95b501209d158bca089135efb236f276a8a4f4ec6b16ca8455ea562764ad
            env:
              ALBUM_LEVELS: "1"
              API_URL: http://immich-api/api/
              IGNORE: "__Videos"
              MODE: CREATE
              READ_ALBUM_PROPERTIES: "True"
              ROOT_PATH: /photos
              SET_ALBUM_THUMBNAIL: random
              SYNC_MODE: "1"
              UNATTENDED: "1"
              TZ: Europe/Warsaw
              API_KEY:
                secretKeyRef:
                  name: immich-secret
                  key: IMMICH_ALBUM_CREATOR_API_KEY
            securityContext: *sc
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 512Mi # Python .__.
      dbbackup:
        containers:
          app:
            image:
              repository: docker.io/prodrigestivill/postgres-backup-local
              tag: 18@sha256:f70742ebe42b2277689b028d1fd15aa80f77cffa01da163cc9f85a6ff1866e7f
            env:
              BACKUP_DIR: "/backups"
              BACKUP_KEEP_DAYS: "14"
              BACKUP_KEEP_WEEKS: "0"
              BACKUP_KEEP_MONTHS: "0"
              BACKUP_KEEP_MINS: "240"
              HEALTHCHECK_PORT: "8080"
              SCHEDULE: "@hourly"
              POSTGRES_EXTRA_OPTS: "-b -C -c -Z6 --inserts"
              POSTGRES_DB: *dbname
              POSTGRES_HOST: *dbhost
              POSTGRES_PASSWORD: *dbpass
              POSTGRES_USER: *dbuser
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 10
              readiness: *probes
            securityContext:
              <<: *sc
              runAsUser: 999
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    service:
      api:
        controller: api
        ports:
          http:
            port: *port
          metrics:
            port: *apiPort
      microservices:
        controller: microservices
        ports:
          metrics:
            port: *msPort
      machinelearning:
        controller: machinelearning
        ports:
          ml-api:
            port: *mlport
    serviceMonitor:
      api:
        serviceName: api
        endpoints:
          - port: metrics
      microservices:
        serviceName: microservices
        endpoints:
          - port: metrics
    route:
      app:
        hostnames:
          - "immich.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: immich-api
                port: 80
            filters:
              - type: ResponseHeaderModifier
                responseHeaderModifier:
                  set:
                    - name: Content-Security-Policy
                      value: >-
                        default-src 'self';
                        connect-src 'self' https://tiles.immich.cloud https://static.immich.cloud;
                        img-src 'self' data:;
                        object-src 'none';
                        script-src 'self' 'unsafe-inline' 'unsafe-eval' blob:;
                        style-src 'self' 'unsafe-inline';
    persistence:
      config:
        type: configMap
        name: immich-configmap
        advancedMounts:
          api: &configMount
            app:
              - subPath: config.yaml
                path: /config/config.yaml
          microservices: *configMount
      data:
        existingClaim: immich
        advancedMounts:
          api: &dataMount
            app:
              - subPath: server-data
                path: /data
          microservices: *dataMount
      dbbackup:
        type: custom
        volumeSpec:
          csi:
            driver: nfs.csi.k8s.io
            volumeAttributes:
              server: nas.internal
              share: "/mnt/fast/backups/kubernetes/${CLUSTER}/databases/immich"
        advancedMounts:
          dbbackup:
            app:
              - path: "/backups"
      homelab-root-ca:
        type: secret
        name: homelab-root-ca
        advancedMounts:
          api: &certMount
            app:
              - path: /certs/homelab.pem
                subPath: ec.crt
          microservices: *certMount
      photos:
        type: custom
        volumeSpec:
          csi:
            driver: nfs.csi.k8s.io
            volumeAttributes:
              server: nas.internal
              share: "/mnt/tank/photos"
        advancedMounts:
          api: &photosMount
            app:
              - path: "/photos"
                readOnly: true
          microservices: *photosMount
          album-creator: *photosMount
      tmp:
        type: emptyDir
        advancedMounts:
          album-creator:
            app:
              - subPath: album-creator
                path: /tmp
          machinelearning:
            app:
              - subPath: machinelearning
                path: /tmp
