---
# yaml-language-server: $schema=https://schemas.ajgon.casa/pocketid.internal/pocketidoidcclient_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: immich
spec:
  launchUrl: https://immich.${ROOT_DOMAIN}
  callbackUrls:
    - "https://immich.${ROOT_DOMAIN}/auth/login"
    - "https://immich.${ROOT_DOMAIN}/user-settings"
  secret:
    additionalLabels:
      reconcile.fluxcd.io/watch: Enabled
    keys:
      clientID: OAUTH_CLIENT_ID
      clientSecret: OAUTH_CLIENT_SECRET
