---
# yaml-language-server: $schema=https://schemas.ajgon.casa/other/docker-compose.json
services:
  borgmatic:
    environment:
      BACKUP_CRON: "30 12 * * *"
      TZ: "Europe/Warsaw"

      BORGMATIC_HOMELAB_ENCRYPTION_PASSPHRASE: "${BORGMATIC_HOMELAB_ENCRYPTION_PASSPHRASE}"
      BORGMATIC_HOMELAB_HC_PING_URL: "${BORGMATIC_HOMELAB_HC_PING_URL}"
      BORGMATIC_HOMELAB_REPO_BORGBASE_EU: "${BORGMATIC_HOMELAB_REPO_BORGBASE_EU}"
      BORGMATIC_HOMELAB_REPO_BORGBASE_US: "${BORGMATIC_HOMELAB_REPO_BORGBASE_US}"
      BORGMATIC_LEGACY_ENCRYPTION_PASSPHRASE: "${BORGMATIC_LEGACY_ENCRYPTION_PASSPHRASE}"
      BORGMATIC_LEGACY_HC_PING_URL: "${BORGMATIC_LEGACY_HC_PING_URL}"
      BORGMATIC_LEGACY_REPO_BORGBASE_EU: "${BORGMATIC_LEGACY_REPO_BORGBASE_EU}"
      BORGMATIC_NAS_ENCRYPTION_PASSPHRASE: "${BORGMATIC_NAS_ENCRYPTION_PASSPHRASE}"
      BORGMATIC_NAS_HC_PING_URL: "${BORGMATIC_NAS_HC_PING_URL}"
      BORGMATIC_NAS_REPO_BORGBASE_EU: "${BORGMATIC_NAS_REPO_BORGBASE_EU}"
      BORGMATIC_NAS_REPO_BORGBASE_US: "${BORGMATIC_NAS_REPO_BORGBASE_US}"
    image: ghcr.io/borgmatic-collective/borgmatic:2.1.5@sha256:6ba3e5226b3c791863fc1bc7c119860782681050ee8951979c511e36b29ab530
    container_name: borgmatic
    restart: always
    configs:
      - source: homelab
        target: /etc/borgmatic.d/homelab.yaml
      - source: legacy
        target: /etc/borgmatic.d/legacy.yaml
      - source: nas
        target: /etc/borgmatic.d/nas.yaml
    volumes:
      - /mnt/cache:/mnt/cache:ro
      - /mnt/tank:/mnt/tank:ro
      - ${DATA_DOCKER_DIR}/borgmatic/config:/config"

configs:
  homelab:
    file: ./config/homelab.yaml
  legacy:
    file: ./config/legacy.yaml
  nas:
    file: ./config/nas.yaml
