---
# yaml-language-server: $schema=https://schemas.rzegocki.dev/other/docker-compose.json
services:
  borgmatic:
    environment:
      CRON: "30 14 * * *"
      TZ: "Europe/Warsaw"

      BORGMATIC_HOMELAB_ENCRYPTION_PASSPHRASE: "${BORGMATIC_HOMELAB_ENCRYPTION_PASSPHRASE}"
      BORGMATIC_HOMELAB_HC_PING_URL: "${BORGMATIC_HOMELAB_HC_PING_URL}"
      BORGMATIC_HOMELAB_REPO_BORGBASE_EU: "${BORGMATIC_HOMELAB_REPO_BORGBASE_EU}"
      BORGMATIC_HOMELAB_REPO_BORGBASE_US: "${BORGMATIC_HOMELAB_REPO_BORGBASE_US}"
      BORGMATIC_NAS_ENCRYPTION_PASSPHRASE: "${BORGMATIC_NAS_ENCRYPTION_PASSPHRASE}"
      BORGMATIC_NAS_HC_PING_URL: "${BORGMATIC_NAS_HC_PING_URL}"
      BORGMATIC_NAS_REPO_BORGBASE_EU: "${BORGMATIC_NAS_REPO_BORGBASE_EU}"
      BORGMATIC_NAS_REPO_BORGBASE_US: "${BORGMATIC_NAS_REPO_BORGBASE_US}"
    image: ghcr.io/borgmatic-collective/borgmatic:2.1.9@sha256:8f3273d0ac5ab7592863d82cd58610c4d5888d284df2c1f12fd1229a99d42db1
    container_name: borgmatic
    restart: always
    configs:
      - source: homelab
        target: /etc/borgmatic.d/homelab.yaml
      - source: nas
        target: /etc/borgmatic.d/nas.yaml
    volumes:
      - /mnt/fast:/mnt/fast:ro
      - /mnt/tank:/mnt/tank:ro
      - ${DATA_DOCKER_DIR}/borgmatic/config:/config

configs:
  homelab:
    file: ./config/homelab.yaml
  nas:
    file: ./config/nas.yaml
