---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bazarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: bazarr-secret
    template:
      data:
        JELLYFIN_API_KEY: "{{ .JELLYFIN_API_KEY }}"
  dataFrom:
    - extract:
        key: kubernetes/media/bazarr
