---
# yaml-language-server: $schema=https://schemas.ajgon.casa/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: openwebui
spec:
  name: openwebui
  owner: app
  cluster:
    name: ai-db
  extensions:
    - ensure: present
      name: vector
    - ensure: present
      name: vchord
