---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: open-webui-secret
    template:
      data:
        OPENAI_API_BASE_URLS: "{{ .OPEN_WEBUI_OPENAI_API_BASE_URLS }}"
        OPENAI_API_KEYS: "{{ .OPEN_WEBUI_OPENAI_API_KEYS }}"
        OAUTH_CLIENT_ID: "{{ .OPEN_WEBUI_CLIENT_ID }}"
        OAUTH_CLIENT_SECRET: "{{ .OPEN_WEBUI_CLIENT_SECRET }}"
        WEBUI_SECRET_KEY: "{{ .OPEN_WEBUI_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: kubernetes
