---
# yaml-language-server: $schema=https://schemas.ajgon.casa/other/app-template-hr.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
spec:
  chartRef:
    kind: OCIRepository
    name: open-webui
  interval: 1h
  values:
    controllers:
      main:
        type: statefulset
        containers:
          app:
            image: &img
              repository: ghcr.io/open-webui/open-webui
              tag: main@sha256:74093dadc9c6aabc23987a74fd8c2fb8d995b1a5b22e83b0036fb9d6af590e8c
            env:
              AUDIO_STT_ENGINE: "openai"
              AUDIO_STT_MODEL: "turbo"
              AUDIO_STT_OPENAI_API_BASE_URL: "http://whisper.ai.svc.cluster.local/v1"
              AUDIO_STT_OPENAI_API_KEY: ""
              AUDIO_TTS_ENGINE: "openai"
              AUDIO_TTS_MODEL: "tts-1"
              AUDIO_TTS_OPENAI_API_BASE_URL: "http://openedai-speech.ai.svc.cluster.local/v1"
              AUDIO_TTS_OPENAI_API_KEY: ""
              AUDIO_TTS_VOICE: "alloy"
              DATABASE_TYPE: postgresql
              DATABASE_NAME: openwebui
              DATABASE_HOST:
                secretKeyRef:
                  name: ai-db-app
                  key: host
              DATABASE_PASSWORD:
                secretKeyRef:
                  name: ai-db-app
                  key: password
              DATABASE_PORT:
                secretKeyRef:
                  name: ai-db-app
                  key: port
              DATABASE_USER:
                secretKeyRef:
                  name: ai-db-app
                  key: username
              ENABLE_FOLLOW_UP_GENERATION: "False"
              ENABLE_LOGIN_FORM: "False"
              ENABLE_OAUTH_SIGNUP: "True"
              ENABLE_OLLAMA_API: "False"
              ENABLE_OPENAI_API: "True"
              ENABLE_PERSISTENT_CONFIG: "False"
              ENABLE_SIGNUP: "False"
              ENABLE_VERSION_UPDATE_CHECK: "False"
              ENABLE_WEB_SEARCH: "True"
              OAUTH_EMAIL_CLAIM: "email"
              OAUTH_GROUP_CLAIM: "groups"
              OAUTH_PROVIDER_NAME: "Pocket ID"
              OAUTH_SCOPES: "openid email profile groups"
              OAUTH_USERNAME_CLAIM: "preferred_username"
              OPENAI_API_BASE_URL: "http://bifrost.ai.svc.cluster.local/v1"
              OPENAI_API_KEY: ""
              OPENID_PROVIDER_URL: "https://id.${ROOT_DOMAIN}/.well-known/openid-configuration"
              REQUESTS_CA_BUNDLE: "/certs/ca-bundle.pem"
              SEARXNG_QUERY_URL: "http://searxng.default.svc.cluster.local/search?q=<query>"
              SSL_CERT_FILE: "/certs/ca-bundle.pem"
              USER_PERMISSIONS_CHAT_STT: "True"
              VECTOR_DB: pgvector
              WEBUI_URL: "https://ai.${ROOT_DOMAIN}"
              WEB_LOADER_ENGINE: "playwright"
              WEB_SEARCH_CONCURRENT_REQUESTS: 10
              WEB_SEARCH_ENGINE: "searxng"
              WEB_SEARCH_RESULT_COUNT: 3
              TZ: Europe/Warsaw
            envFrom:
              - secretRef:
                  name: "open-webui-secret"
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8080
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
                add:
                  - CHOWN
                  - DAC_OVERRIDE
                  - FOWNER
                  - KILL
                  - SETGID
                  - SETUID
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 4096Mi
        initContainers:
          01-merge-certificates:
            image: *img
            command:
              - sh
              - -c
              - >-
                cat /etc/ssl/certs/ca-certificates.crt /certs/homelab.pem
                > /certs/ca-bundle.pem
        statefulset:
          volumeClaimTemplates:
            - name: data
              storageClass: ceph-block
              accessMode: ReadWriteOnce
              size: 5Gi
              advancedMounts:
                app:
                  - path: /root/.cache
                    subPath: root-cache
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      labels:
        egress.cilium.io/auth: "true"
        egress.cilium.io/search: "true"
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        ports:
          http:
            appProtocol: kubernetes.io/wss
            port: 80
            targetPort: *port
    route:
      app:
        hostnames:
          - "ai.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: open-webui
                port: 80
            filters:
              - type: ResponseHeaderModifier
                responseHeaderModifier:
                  set:
                    - name: Content-Security-Policy
                      value: >-
                        default-src 'self' data: blob:;
                        object-src 'self';
                        script-src 'self' 'unsafe-inline' 'unsafe-eval';
                        style-src 'self' 'unsafe-inline';
    persistence:
      config:
        existingClaim: "open-webui"
        globalMounts:
          - path: /app/backend/data
      homelab-ca:
        type: secret
        name: homelab-root-ca.crt
        globalMounts:
          - path: /certs/homelab.pem
            subPath: ec.crt
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
          - path: /certs
            subPath: certs
