# workaround: https://old.reddit.com/r/selfhosted/comments/omwb2j/comment/hrtznxj/
tokeninfo_url = https://id.${ROOT_DOMAIN}/api/oidc/userinfo?dummy=
introspection_mode = auth
introspection_url = https://${OAUTH_CLIENT_ID}:${OAUTH_CLIENT_SECRET}@id.${ROOT_DOMAIN}/api/oidc/introspect
force_introspection = no
username_attribute = email
tls_ca_cert_file = /etc/ssl/certs/ca-certificates.crt
