---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sabnzbd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: sabnzbd-secret
    template:
      data:
        SABNZBD__API_KEY: "{{ .SABNZBD__API_KEY }}"
        SABNZBD__NZB_KEY: "{{ .SABNZBD__API_KEY }}" # same as api key
  dataFrom:
    - extract:
        key: kubernetes/media/sabnzbd
