---
# yaml-language-server: $schema=https://schemas.ajgon.casa/other/forgejo-hr.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
spec:
  chartRef:
    kind: OCIRepository
    name: forgejo
  interval: 30m
  values:
    gitea:
      admin:
        username: ""
      additionalConfigSources:
        - secret:
            secretName: forgejo-secret
      config:
        actions:
          DEFAULT_ACTIONS_URL: https://github.com
        admin:
          DISABLE_REGULAR_ORG_CREATION: false
        attachment:
          ENABLED: true
          MAX_SIZE: 64
          PATH: /data/data/attachments
          STORAGE_TYPE: local
        avatar:
          PATH: /data/data/avatars
          STORAGE_TYPE: local
        badges:
          ENABLED: true
        cache:
          ENABLED: true
          ADAPTER: redis
          HOST: redis://forgejo-dragonfly:6379?pool_size=100&idle_timeout=180s
        cron.archive_cleanup:
          ENABLED: true
          OLDER_THAN: 2h
          RUN_AT_START: true
          SCHEDULE: "@every 1h"
        database:
          DB_TYPE: sqlite3
          PATH: /data/data/database/forgejo.db
        federation:
          ENABLED: false
        indexer:
          ISSUE_INDEXER_TYPE: bleve
          REPO_INDEXER_ENABLED: true
        lfs:
          PATH: /data/git/lfs
        log:
          MODE: console
        log.console:
          COLORIZE: false
          FLAGS: journaldflags
          STDERR: true
        mailer:
          ENABLED: true
          FROM: "deedee@${ROOT_DOMAIN}"
          HELO_HOSTNAME: "${ROOT_DOMAIN}"
          PROTOCOL: smtp
          SMTP_ADDR: smtp-relay.network.svc.cluster.local
          SMTP_PORT: "25"
          SUBJECT_PREFIX: "[FORGEJO]"
        openid:
          ENABLE_OPENID_SIGNIN: false
          ENABLE_OPENID_SIGNUP: false
          WHITELISTED_URIS: "id.${ROOT_DOMAIN}"
        picture:
          DISABLE_GRAVATAR: true
          ENABLE_FEDERATED_AVATAR: false
        queue:
          CONN_STR: redis://forgejo-dragonfly:6379?pool_size=100&idle_timeout=180s
          TYPE: redis
        repo-avatar:
          PATH: /data/data/repo-avatars
          STORAGE_TYPE: local
        repository:
          DEFAULT_BRANCH: master
          DEFAULT_PRIVATE: private
          DEFAULT_REPO_UNITS: repo.code,repo.releases,repo.issues,repo.pulls,repo.actions
          DISABLED_REPO_UNITS: repo.ext_wiki,repo.ext_issues
          DISABLE_STARS: true
          ROOT: /data/git/repositories
        repository.pull-request:
          DEFAULT_MERGE_STYLE: squash
        repository.signing:
          CRUD_ACTIONS: pubkey, parentsigned
          FORMAT: ssh
          INITIAL_COMMIT: pubkey
          MERGES: pubkey
          SIGNING_EMAIL: "noreply@git.${ROOT_DOMAIN}"
          SIGNING_KEY: /data/signing/ed25519.pub
          SIGNING_NAME: "git.${ROOT_DOMAIN} Instance"
          WIKI: never
        security:
          INSTALL_LOCK: true
          REVERSE_PROXY_TRUSTED_PROXIES: 172.30.0.0/16
        server:
          DOMAIN: "git.${ROOT_DOMAIN}"
          ENABLE_PPROF: false
          OFFLINE_MODE: true
          ROOT_URL: "https://git.${ROOT_DOMAIN}"
          SSH_DOMAIN: "git.${ROOT_DOMAIN}"
          SSH_PORT: &sshPort 22
        service:
          ALLOW_ONLY_EXTERNAL_REGISTRATION: true
          DEFAULT_ALLOW_CREATE_ORGANIZATION: true
          DEFAULT_ENABLE_TIMETRACKING: false
          DISABLE_REGISTRATION: false
          ENABLE_INTERNAL_SIGNIN: false
          ENABLE_NOTIFY_MAIL: true
          ENABLE_PASSWORD_SIGNIN_FORM: false
          SHOW_REGISTRATION_BUTTON: false
        service.explore:
          DISABLE_CODE_PAGE: false
          DISABLE_ORGANIZATIONS_PAGE: false
          DISABLE_USERS_PAGE: true
          REQUIRE_SIGNIN_VIEW: false
        session:
          PROVIDER: redis
          PROVIDER_CONFIG: redis://forgejo-dragonfly:6379?pool_size=100&idle_timeout=180s
          SESSION_LIFE_TIME: "1209600"
        storage:
          STORAGE_TYPE: local
        time:
          DEFAULT_UI_LOCATION: &tz "Europe/Warsaw"
        ui:
          DEFAULT_THEME: forgejo-dark
        webhook:
          ALLOWED_HOST_LIST: "*"
      oauth:
        - name: Pocket ID
          adminGroup: admins
          autoDiscoverUrl: https://id.${ROOT_DOMAIN}/.well-known/openid-configuration
          existingSecret: forgejo-oidc-credentials
          groupClaimName: groups
          provider: openidConnect
          scopes: profile email groups
    deployment:
      annotations:
        glance/name: Forgejo
        glance/icon: di:forgejo
        glance/url: https://git.${ROOT_DOMAIN}
      env:
        - name: TZ
          value: *tz
      labels:
        egress.cilium.io/auth: "true"
        egress.cilium.io/internet: "true"
        egress.cilium.io/nas: "true"
        egress.cilium.io/smtp-relay: "true"
    dnsConfig:
      options:
        - name: ndots
          value: "1"
    extraContainerVolumeMounts:
      - name: signing-key
        mountPath: /data/signing
        readOnly: true
      - name: homelab-root-ca
        mountPath: /etc/ssl/certs/homelab.crt
        subPath: ec.crt
        readOnly: true
    extraInitVolumeMounts:
      - name: signing-key
        mountPath: /data/signing
        readOnly: true
      - name: homelab-root-ca
        mountPath: /etc/ssl/certs/homelab.crt
        subPath: ec.crt
        readOnly: true
    extraVolumes:
      - name: homelab-root-ca
        secret:
          secretName: homelab-root-ca
          defaultMode: 0400
      - name: signing-key
        secret:
          secretName: forgejo-signing-key-secret
          defaultMode: 0400
    httpRoute:
      enabled: false
    image:
      rootless: true
      registry: code.forgejo.org
      repository: forgejo/forgejo
      tag: 15.0.5-rootless
    persistence:
      create: false
      claimName: forgejo
    service:
      ssh:
        port: *sshPort
    tcpRoute:
      enabled: true
      parentRefs:
        - name: envoy-internal
          namespace: network
          sectionName: ssh
