---
# yaml-language-server: $schema=https://schemas.rzegocki.dev/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: bookorbit
spec:
  name: bookorbit
  owner: app
  cluster:
    name: media-db
  extensions:
    - ensure: present
      name: vector
