---
# yaml-language-server: $schema=https://schemas.rzegocki.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bookorbit
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: bookorbit-secret
    template:
      data:
        JWT_SECRET: "{{ .JWT_SECRET }}"
        SETUP_BOOTSTRAP_TOKEN: "{{ .SETUP_BOOTSTRAP_TOKEN }}"
  dataFrom:
    - extract:
        key: kubernetes/media/bookorbit
