# attic.toml
[storage]
type = "s3"
region = "eu-central-1"
bucket = "nix"
endpoint = "https://s3.ajgon.casa"

[database]
url = "sqlite:///var/lib/attic/server.db?mode=rwc"

[chunking]
nar-size-threshold = 33554432
min-size = 2097152
avg-size = 8388608
max-size = 33554432
