---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes-agent
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: hermes-agent-secret
    template:
      data:
        API_SERVER_KEY: "{{ .API_SERVER_KEY }}"
        DISCORD_BOT_TOKEN: "{{ .DISCORD_BOT_TOKEN }}"
        DISCORD_ALLOWED_USERS: "{{ .DISCORD_ALLOWED_USERS }}"
        DISCORD_HOME_CHANNEL: "{{ .DISCORD_HOME_CHANNEL }}"
  dataFrom:
    - extract:
        key: kubernetes/ai/hermes-agent
