---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes-agent
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: hermes-agent-secret
    template:
      data:
        API_SERVER_KEY: "{{ .API_SERVER_KEY }}"
        HERMES_DASHBOARD_BASIC_AUTH_USERNAME: "{{ .HERMES_DASHBOARD_BASIC_AUTH_USERNAME }}"
        HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: "{{ .HERMES_DASHBOARD_BASIC_AUTH_PASSWORD }}"
        HERMES_DASHBOARD_BASIC_AUTH_SECRET: "{{ .HERMES_DASHBOARD_BASIC_AUTH_SECRET }}"
  dataFrom:
    - extract:
        key: kubernetes/ai/hermes-agent
