---
# yaml-language-server: $schema=https://schemas.ajgon.casa/pocketid.internal/pocketidoidcclient_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: hermes-agent
spec:
  launchUrl: https://hermes.${ROOT_DOMAIN}
  isPublic: true
  secret:
    keys:
      clientID: HERMES_DASHBOARD_OIDC_CLIENT_ID
