---
# yaml-language-server: $schema=https://schemas.ajgon.casa/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgresql
spec:
  components:
    - ./components/postgresql
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      namespace: immich-system
      name: immich-db
  healthCheckExprs:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      current: has(status.conditions) && status.conditions.exists(e, e.type == 'Ready' && e.status == 'True')
      failed: >-
        has(status.phase) && status.phase in [
          'Cluster cannot execute instance online upgrade due to missing architecture binary',
          'Cluster cannot proceed to reconciliation due to an error while interacting with plugins',
          'Cluster cannot proceed to reconciliation due to an unknown plugin being required',
          'Cluster has incomplete or invalid image catalog',
          'Cluster is unrecoverable and needs manual intervention',
          'Invalid cluster definition',
          'Unable to create required cluster objects',
          'Waiting for user action'
        ]
  interval: 1h
  patches:
    - patch: |-
        apiVersion: postgresql.cnpg.io/v1
        kind: Cluster
        metadata:
          name: _
        spec:
          bootstrap:
            initdb:
              postInitApplicationSQL:
                - CREATE ROLE anon NOLOGIN NOINHERIT;
                - CREATE ROLE authenticated NOLOGIN NOINHERIT;
                - CREATE ROLE service_role NOLOGIN NOINHERIT BYPASSRLS;
                - CREATE ROLE authenticator NOLOGIN NOINHERIT;
                - CREATE ROLE supabase_auth_admin NOLOGIN NOINHERIT CREATEROLE;
                - CREATE ROLE supabase_storage_admin NOLOGIN NOINHERIT;
                - GRANT anon, authenticated, service_role TO authenticator;
                - GRANT anon, authenticated, service_role, supabase_auth_admin, supabase_storage_admin TO app;
                - CREATE SCHEMA IF NOT EXISTS auth AUTHORIZATION app;
                - CREATE SCHEMA IF NOT EXISTS storage AUTHORIZATION app;
                - GRANT USAGE ON SCHEMA storage TO anon, authenticated, service_role;
                - >-
                  ALTER DEFAULT PRIVILEGES FOR ROLE app IN SCHEMA storage
                  GRANT ALL ON TABLES TO anon, authenticated, service_role;
                - >-
                  ALTER DEFAULT PRIVILEGES FOR ROLE app IN SCHEMA storage
                  GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;
      target:
        group: postgresql.cnpg.io
        kind: Cluster
  path: ./kubernetes
  postBuild:
    substitute:
      APP: shelf
      ROOT_DOMAIN: "${ROOT_DOMAIN}"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: shelf-system
  wait: true
