---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: renovate-secret
    template:
      data:
        RENOVATE_GITHUB_COM_TOKEN: "{{ .RENOVATE_GITHUB_COM_TOKEN }}"
        RENOVATE_TOKEN: "{{ .RENOVATE_TOKEN }}"
  dataFrom:
    - extract:
        key: kubernetes/forgejo-system/renovate
