---
# yaml-language-server: $schema=https://schemas.ajgon.casa/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: forgejo
spec:
  discoveryFilters:
    - deedee/claude
    - deedee/mark13
    - deedee/schemas
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: GIT_SSL_CAINFO
      value: &certs /certs/homelab.pem
    - name: NODE_EXTRA_CA_CERTS
      value: *certs
    - name: RENOVATE_DETECT_HOST_RULES_FROM_ENV
      value: "true"
  extraVolumes:
    - name: homelab-ca
      secret:
        defaultMode: 420
        secretName: homelab-root-ca.crt
  extraVolumeMounts:
    - mountPath: /certs/homelab.pem
      name: homelab-ca
      subPath: ec.crt
  image: ghcr.io/renovatebot/renovate:43.251.2
  metadata:
    labels:
      app.kubernetes.io/name: renovate-job
      egress.cilium.io/internet: "true"
  parallelism: 5
  provider:
    name: forgejo
    endpoint: https://git.${ROOT_DOMAIN}/api/v1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 0 * * * *
  secretRef: renovate-secret
  webhook:
    enabled: false
