---
# yaml-language-server: $schema=https://schemas.ajgon.casa/other/app-template-hr.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oxicloud
spec:
  chartRef:
    kind: OCIRepository
    name: oxicloud
  interval: 1h
  values:
    controllers:
      app:
        containers:
          app:
            image:
              repository: diocrafts/oxicloud
              tag: 0.5.1@sha256:b76a9598543ca67844702ea17b9636601d357059cd538d25ba577ea660c1742e
            command:
              - oxicloud
            env:
              OXICLOUD_STORAGE_PATH: /data
              OXICLOUD_SERVER_PORT: &port 8086 # for some reason port is ignored
              OXICLOUD_SERVER_HOST: 0.0.0.0
              OXICLOUD_BASE_URL: https://oxicloud.${ROOT_DOMAIN}
              OXICLOUD_OIDC_ENABLED: "true"
              OXICLOUD_OIDC_ADMIN_GROUPS: "admins"
              OXICLOUD_OIDC_AUTO_PROVISION: "false"
              OXICLOUD_OIDC_DISABLE_PASSWORD_LOGIN: "false"
              OXICLOUD_OIDC_FRONTEND_URL: https://oxicloud.${ROOT_DOMAIN}
              OXICLOUD_OIDC_ISSUER_URL: http://pocket-id.security.svc.cluster.local:8080
              OXICLOUD_OIDC_PROVIDER_NAME: "Pocket ID"
              OXICLOUD_OIDC_REDIRECT_URI: https://oxicloud.${ROOT_DOMAIN}/api/auth/oidc/callback
              OXICLOUD_DB_CONNECTION_STRING:
                secretKeyRef:
                  name: oxicloud-db-app
                  key: fqdn-uri
            envFrom:
              - secretRef:
                  name: oxicloud-secret
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext: &sc
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
      dbbackup:
        containers:
          app:
            image:
              repository: docker.io/prodrigestivill/postgres-backup-local
              tag: 18@sha256:f70742ebe42b2277689b028d1fd15aa80f77cffa01da163cc9f85a6ff1866e7f
            env:
              BACKUP_DIR: "/backups"
              BACKUP_KEEP_DAYS: "14"
              BACKUP_KEEP_WEEKS: "0"
              BACKUP_KEEP_MONTHS: "0"
              BACKUP_KEEP_MINS: "240"
              HEALTHCHECK_PORT: "8080"
              SCHEDULE: "@hourly"
              POSTGRES_EXTRA_OPTS: "-b -C -c -Z6 --inserts"
              POSTGRES_DB:
                secretKeyRef:
                  name: oxicloud-db-app
                  key: dbname
              POSTGRES_HOST:
                secretKeyRef:
                  name: oxicloud-db-app
                  key: host
              POSTGRES_PASSWORD:
                secretKeyRef:
                  name: oxicloud-db-app
                  key: password
              POSTGRES_USER:
                secretKeyRef:
                  name: oxicloud-db-app
                  key: username
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 10
              readiness: *probes
            securityContext:
              <<: *sc
              runAsUser: 999
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      labels:
        egress.cilium.io/auth: "true"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        controller: app
        ports:
          http:
            port: 80
            targetPort: *port
    route:
      app:
        hostnames:
          - "oxicloud.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: oxicloud
                port: 80
            filters:
              - type: ResponseHeaderModifier
                responseHeaderModifier:
                  set:
                    - name: Content-Security-Policy
                      value: >-
                        default-src 'self';
                        script-src 'self' 'unsafe-inline';
                        style-src 'self' 'unsafe-inline';
    persistence:
      data:
        existingClaim: oxicloud
        advancedMounts:
          app:
            app:
              - subPath: storage
                path: /data
      dbbackup:
        type: custom
        volumeSpec:
          csi:
            driver: nfs.csi.k8s.io
            volumeAttributes:
              server: nas.internal
              share: "/mnt/cache/backups/kubernetes/${CLUSTER}/databases/oxicloud"
        advancedMounts:
          dbbackup:
            app:
              - path: "/backups"
      tmp:
        type: emptyDir
