---
# yaml-language-server: $schema=https://schemas.ajgon.casa/other/app-template-hr.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: syncthing
spec:
  chartRef:
    kind: OCIRepository
    name: syncthing
  interval: 1h
  values:
    controllers:
      main:
        containers:
          app:
            image:
              repository: ghcr.io/syncthing/syncthing
              tag: 2.0.16@sha256:4a961394ca471f4e48f31ad2cef50697e502c8799e2e98477a1c3844e0c5bc54
            env:
              STHOMEDIR: /config
              TZ: Europe/Warsaw
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /rest/noauth/health
                    port: &port 8384
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2048Mi
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        ports:
          http:
            port: 80
            targetPort: *port
          sync:
            protocol: TCP
            port: &sync 22000
    serviceMonitor:
      app:
        endpoints:
          - port: http
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |
            name: syncthing
        hostnames:
          - "syncthing.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: syncthing
                port: 80
            filters:
              - type: ResponseHeaderModifier
                responseHeaderModifier:
                  set:
                    - name: Content-Security-Policy
                      value: >-
                        default-src 'self';
                        object-src 'none';
                        script-src 'self' 'unsafe-inline' 'unsafe-eval';
                        style-src 'self' 'unsafe-inline';
      sync:
        kind: TCPRoute
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: syncthing
        rules:
          - backendRefs:
              - name: syncthing
                port: *sync
    persistence:
      config:
        existingClaim: syncthing
        advancedMounts:
          main:
            app:
              - path: /config
                subPath: config
              - path: /data
                subPath: data
            01-set-config:
              - path: /config
                subPath: config
      external-sync:
        type: custom
        volumeSpec:
          csi:
            driver: nfs.csi.k8s.io
            volumeAttributes:
              server: nas.internal
              share: "/mnt/cache/merger/sync"
              mountOptions: "noac,nfsvers=4.1,nconnect=16,hard,noatime"
        advancedMounts:
          main:
            app:
              - path: "/sync"
      tmp:
        type: emptyDir
        medium: Memory
        sizeLimit: 32Mi
        globalMounts:
          - subPath: tmp
            path: /tmp
