---
# yaml-language-server: $schema=https://schemas.rzegocki.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chhoto-url
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: chhoto-url-secret
    template:
      data:
        CHHOTO_API_KEY: "{{ .CHHOTO_API_KEY }}"
        CHHOTO_PASSWORD: "{{ .CHHOTO_PASSWORD }}"
  dataFrom:
    - extract:
        key: kubernetes/default/chhoto-url
