---
# yaml-language-server: $schema=https://schemas.rzegocki.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ${APP}-db
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  instances: 3
  # renovate: depName=ghcr.io/tensorchord/cloudnative-vectorchord versioning=double
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18.6-1.1.1@sha256:c7672bc011351a587cc292a94aac7eeebb593ed2e120077bd9c9944c9467db93
  enableSuperuserAccess: false
  inheritedMetadata:
    labels:
      egress.cilium.io/kube-apiserver: "true"
      egress.cilium.io/nas: "true"
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  stopDelay: 180
  smartShutdownTimeout: 180
  storage:
    size: ${PGDB_CAPACITY:=10Gi}
    storageClass: ${PGDB_STORAGE_CLASS:=ceph-block}
  walStorage:
    size: ${PGDB_WAL_CAPACITY:=8Gi}
    storageClass: ${PGDB_STORAGE_CLASS:=ceph-block}
  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: 512MB
      max_slot_wal_keep_size: 3GB
  monitoring:
    enablePodMonitor: true
  priorityClassName: cnpg-instance
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: ${APP}-db-store
        serverName: ${APP}-db
  externalClusters:
    - name: ${APP}-db-restore
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: ${APP}-db-store
          serverName: ${APP}-db
