---
# yaml-language-server: $schema=https://schemas.ajgon.casa/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ${APP}-db
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  instances: 3
  # renovate: depName=ghcr.io/tensorchord/cloudnative-vectorchord versioning=double
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18.3-1.1.1@sha256:392b53675b403d6a2c72b673cc488a7c272514755dd818c622fb9ce4665193c4
  enableSuperuserAccess: false
  inheritedMetadata:
    labels:
      egress.cilium.io/kube-apiserver: "true"
      egress.cilium.io/nas: "true"
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  stopDelay: 180
  smartShutdownTimeout: 180
  storage:
    size: ${PGDB_CAPACITY:=10Gi}
    storageClass: ${PGDB_STORAGE_CLASS:=ceph-block}
  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: 512MB
  monitoring:
    enablePodMonitor: true
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: ${APP}-db-store
        serverName: ${APP}-db
  externalClusters:
    - name: ${APP}-db-restore
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: ${APP}-db-store
          serverName: ${APP}-db
