---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-db-store
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: ${APP}-db-store-secret
    template:
      data:
        ACCESS_KEY_ID: "{{ .ACCESS_KEY_ID }}"
        ACCESS_SECRET_KEY: "{{ .ACCESS_SECRET_KEY }}"
        AWS_REGION: "eu-central-1"
  dataFrom:
    - extract:
        key: kubernetes/_components/postgresql
