---
# yaml-language-server: $schema=https://schemas.ajgon.casa/other/docker-compose.json
services:
  mongo:
    image: public.ecr.aws/docker/library/mongo:8.2.6@sha256:eea8506335198f8b359865b32004036310854a935fbd317083817c614152818f
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    command: --quiet --wiredTigerCacheSizeGB 0.25
    restart: unless-stopped
    env_file:
      - ./compose.env
      - ./override.env
    volumes:
      - "${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}/volumes/komodo/mongo/data:/data/db"
      - "${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}/volumes/komodo/mongo/config:/data/configdb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${KOMODO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${KOMODO_DB_PASSWORD}

  core:
    image: ghcr.io/moghtech/komodo-core:2.1.1@sha256:2bbbb1efd3534211dac35091e0818f10398d9bdd98fdbf0ddef09e9e0b5ec4ba
    init: true
    restart: unless-stopped
    depends_on:
      - mongo
    env_file:
      - ./compose.env
      - ./override.env
      - ./.env
    volumes:
      - "${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}/volumes/komodo/config.toml:/config/config.toml"
      - "${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}/volumes/komodo/backups:/backups"
      - "${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}/volumes/komodo/keys:/config/keys"
      - "${SOPS_AGE_KEY_FILE:-/etc/age/keys.txt}:/etc/age/keys.txt"
      - "/etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt"
    environment:
      KOMODO_DATABASE_ADDRESS: mongo:27017
      KOMODO_DATABASE_USERNAME: ${KOMODO_DB_USERNAME}
      KOMODO_DATABASE_PASSWORD: ${KOMODO_DB_PASSWORD}
    # ports:
    #   - 9120:9120
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
      - internal
    # traefik
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
      traefik.enable: "true"
      traefik.http.services.komodo.loadbalancer.server.port: "9120"
      traefik.http.routers.komodo.entrypoints: https
      traefik.http.routers.komodo.rule: Host(`komodo.${ROOT_DOMAIN}`)
      traefik.http.routers.komodo.service: komodo
      traefik.http.routers.komodo.tls: true
      traefik.http.routers.komodo.tls.certresolver: vault-ecdsa
      traefik.http.routers.komodo.tls.domains[0].main: 'komodo.${ROOT_DOMAIN}'

networks:
  internal:
    name: internal
    external: true
