---
# yaml-language-server: $schema=https://schemas.ajgon.casa/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: toolhive-operator
spec:
  chartRef:
    kind: OCIRepository
    name: toolhive-operator
  interval: 30m
  values:
    operator:
      podLabels:
        egress.cilium.io/kube-apiserver: "true"
      env:
        - name: TOOLHIVE_SKIP_UPDATE_CHECK
          value: "true"
      replicaCount: 1
