---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: runner-secret
    template:
      data:
        token: "{{ .RUNNER_K8S_TOKEN }}"
        uuid: "{{ .RUNNER_K8S_UUID }}"
  dataFrom:
    - extract:
        key: kubernetes/forgejo-system/runner
