---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bifrost
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: bifrost-secret
    template:
      data:
        config.json: |
          {
            "$schema": "https://www.getbifrost.ai/schema",
            "encryption_key": "{{ .BIFROST_ENCRYPTION_KEY }}",
            "client": {
              "drop_excess_requests": false,
              "enable_logging": true
            },
            "providers": {{ .BIFROST_PROVIDERS }},
            "source_of_truth": "config.json"
          }
  dataFrom:
    - extract:
        key: kubernetes/ai/bifrost
