---
# yaml-language-server: $schema=https://schemas.ajgon.casa/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: bifrost-egress-internal
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: bifrost
  egress:
    - toEndpoints:
        - {}
    - toCIDRSet:
        - cidr: 192.168.2.0/24
      toPorts:
        - ports:
            - port: "80"
            - port: "443"
    - toFQDNs:
        - matchName: getbifrost.ai
      toPorts:
        - ports:
            - port: "443"
