---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
components:
  - ../../../../components/namespace
resources:
  - ./_namespace.yaml
  - ./cloudnative-pg.yaml
  - ./dragonfly-operator.yaml
  - ./plugin-barman-cloud.yaml
