---
# yaml-language-server: $schema=https://schemas.ajgon.casa/pocketid.internal/pocketidoidcclient_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: ${APP}
spec:
  launchUrl: https://${APP}.${ROOT_DOMAIN}
  callbackUrls:
    - "https://${APP}.${ROOT_DOMAIN}/oauth2/callback"
  allowedUserGroups:
    - name: admins
      namespace: security
  secret:
    keys:
      clientID: client-id
      clientSecret: client-secret
