---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mail-archive
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: mail-archive-secret
    template:
      data:
        DESTINATION_PASS: "{{ .IMAPSYNC_DESTINATION_PASS }}"
        DESTINATION_USER: "{{ .IMAPSYNC_DESTINATION_USER }}"
        DOVECOT_PASSWD: "{{ .IMAPSYNC_DESTINATION_USER }}:{{ .IMAPSYNC_DESTINATION_PASS }}:::"
        SOURCE_PASS: "{{ .IMAPSYNC_SOURCE_PASS }}"
        SOURCE_USER: "{{ .IMAPSYNC_SOURCE_USER }}"
  dataFrom:
    - extract:
        key: kubernetes/default/mail-archive
