---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-operator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: pocket-id-operator-secret
    template:
      data:
        ENCRYPTION_KEY: "{{ .ENCRYPTION_KEY }}"
        MAXMIND_LICENSE_KEY: "{{ .MAXMIND_LICENSE_KEY }}"
  dataFrom:
    - extract:
        key: kubernetes/security/pocket-id
