---
# yaml-language-server: $schema=https://schemas.rzegocki.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hindsight
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: hindsight-secret
    template:
      data:
        HINDSIGHT_API_LLM_MODEL: "{{ .HINDSIGHT_API_LLM_MODEL }}"
        HINDSIGHT_API_LLM_API_KEY: "{{ .HINDSIGHT_API_LLM_API_KEY }}"
        HINDSIGHT_API_TENANT_API_KEY: "{{ .HINDSIGHT_API_TENANT_API_KEY }}"
        HINDSIGHT_CP_DATAPLANE_API_KEY: "{{ .HINDSIGHT_API_TENANT_API_KEY }}"
  dataFrom:
    - extract:
        key: kubernetes/ai/hindsight
