---
# yaml-language-server: $schema=https://schemas.rzegocki.dev/other/app-template-hr.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calino
spec:
  chartRef:
    kind: OCIRepository
    name: calino
  interval: 1h
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
          glance/name: calino
          glance/icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/calino.png
          glance/url: &url https://calino.${ROOT_DOMAIN}
        containers:
          app:
            image:
              repository: ghcr.io/ivan-malinovski/calino
              tag: 0.33.7@sha256:4fb2b0e97f4e1da51ba3f7381b373c5d6987a65aea143f8867d1c5809ec432fd
            env:
              VITE_SITE_URL: *url
              TZ: Europe/Warsaw
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8080
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
                add:
                  - NET_BIND_SERVICE
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 2Gi
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        ports:
          http:
            port: 80
            targetPort: *port
    route:
      app:
        hostnames:
          - "calino.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: calino
                port: 80
            filters:
              - type: ResponseHeaderModifier
                responseHeaderModifier:
                  set:
                    - name: Content-Security-Policy
                      value: >-
                        default-src 'self' data: blob:;
                        connect-src 'self' https://davis.${ROOT_DOMAIN};
                        object-src 'none';
                        script-src 'self' 'unsafe-inline' 'unsafe-eval';
                        style-src 'self' 'unsafe-inline';
    persistence:
      tmp:
        type: emptyDir
        medium: Memory
        sizeLimit: 128Mi
        globalMounts:
          - subPath: config
            path: /config
          - subPath: data
            path: /data
