---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: searxng-secret
    template:
      data:
        SEARXNG_SECRET: "{{ .SEARXNG_SECRET }}"
  dataFrom:
    - extract:
        key: kubernetes/default/searxng
