---
# yaml-language-server: $schema=https://schemas.ajgon.casa/other/ansible.json#/$defs/tasks
- name: Reload sshd
  ansible.builtin.systemd_service:
    name: "{{ user_sshd_service }}"
    state: reloaded
