---
# yaml-language-server: $schema=https://schemas.rzegocki.dev/other/ansible.json#/$defs/tasks
- name: Reload sshd
  ansible.builtin.systemd_service:
    name: "{{ user_sshd_service }}"
    state: reloaded
