---
# yaml-language-server: $schema=https://schemas.rzegocki.dev/other/docker-compose.json
services:
  smartctl-exporter:
    image: quay.io/prometheuscommunity/smartctl-exporter:v0.15.0@sha256:4b2b5c9912c95899ad4720b3ada368e7b0d46f4c2fd6dc7d174922c325ef9855
    container_name: smartctl-exporter
    restart: unless-stopped
    ports:
      - '9633:9633'
    privileged: true
    read_only: true
    user: root
