---
server:
  bind: :8080
metadata:
  directory: /config
  dlc_mapper:
    CUSA12152: CUSA12153
    CUSA12421: CUSA12401
    CUSA17776: CUSA20177
    CUSA34386: CUSA34390
  game_title_mapper:
    CUSA03551: Bully
    BLES01227: "ASURA'S WRATH"
  title_replacements:
    "™": ""
    "®": ""
    "ö": "o"
    "by 14QwerT88": ""
    "By PsHack": ""
pkgs:
  directory: /data
  filter:
    - PS3
    - PS4
scanner:
  poll_interval: 30s
