---
# yaml-language-server: $schema=https://schemas.ajgon.casa/toolhive.stacklok.dev/mcpserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: talos-mcp
spec:
  image: registry.erwanleboucher.dev/eleboucher/talos-mcp:0.0.2
  groupRef:
    name: mcp-tools
  env:
    - name: TALOS_MCP_TRANSPORT
      value: http
    - name: TALOS_MCP_HTTP_ADDR
      value: ":8080"
  podTemplateSpec:
    metadata:
      labels:
        egress.cilium.io/talos-apiserver: "true"
    spec:
      containers:
        - name: mcp
          volumeMounts:
            - name: talosconfig
              mountPath: /var/run/secrets/talos.dev
              readOnly: true
      volumes:
        - name: talosconfig
          secret:
            secretName: talos-mcp-talosconfig
            defaultMode: 0400
  transport: streamable-http
