---
# yaml-language-server: $schema=https://schemas.ajgon.casa/pocketid.internal/pocketidoidcclient_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: karakeep
spec:
  launchUrl: https://karakeep.${ROOT_DOMAIN}
  callbackUrls:
    - "https://karakeep.${ROOT_DOMAIN}/api/auth/callback/custom"
  secret:
    additionalLabels:
      reconcile.fluxcd.io/watch: Enabled
    keys:
      clientID: OAUTH_CLIENT_ID
      clientSecret: OAUTH_CLIENT_SECRET
