---
# yaml-language-server: $schema=https://schemas.rzegocki.dev/other/ansible-meta.json
galaxy_info:
  role_name: docker
  author: ajgon
  description: Install Docker CE with the compose and buildx plugins
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - docker
dependencies: []
