---
# yaml-language-server: $schema=https://schemas.rzegocki.dev/other/docker-compose.json
services:
  towonel-agent:
    environment:
      RUST_LOG: info
      TOWONEL_INVITE_TOKEN: "${TOWONEL_INVITE_TOKEN}"
      TOWONEL_AGENT_TCP_SERVICES: |-
        [
          {"name":"rustdesk-nat","origin":"127.0.0.1:21115","listen_port":21115},
          {"name":"rustdesk-conn","origin":"127.0.0.1:21116","listen_port":21116},
          {"name":"rustdesk-relay","origin":"127.0.0.1:21117","listen_port":21117}
        ]
      TOWONEL_AGENT_UDP_SERVICES: |-
        [
          {"name":"rustdesk-id","origin":"127.0.0.1:21116","listen_port":21116},
          {"name":"wireguard","origin":"127.0.0.1:57968","listen_port":57968}
        ]
    image: codeberg.org/towonel/towonel-agent:1.5.3
    container_name: towonel-agent
    restart: unless-stopped
    network_mode: host
