---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: paperless-ngx-secret
    template:
      data:
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: kubernetes/default/paperless-ngx
