---
# yaml-language-server: $schema=https://schemas.ajgon.casa/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: paperless-ngx-oidc-secret
stringData:
  PAPERLESS_SOCIALACCOUNT_PROVIDERS: |-
    {
      "openid_connect": {
        "SCOPE": ["openid","profile","email","groups"],
        "OAUTH_PKCE_ENABLED": true,
        "APPS": [
          {
            "provider_id": "pocket-id",
            "name": "Pocket ID",
            "client_id": "${OAUTH_CLIENT_ID}",
            "secret": "${OAUTH_CLIENT_SECRET}",
            "settings": {
              "fetch_userinfo": true,
              "oauth_pkce_enabled": true,
              "server_url": "https://id.${ROOT_DOMAIN}"
            }
          }
        ]
      }
    }
