---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./database.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./networkpolicy.yaml
  - ./ocirepository.yaml
  - ./pocketidoidcclient.yaml
configMapGenerator:
  - name: shelf-oidc-shim-configmap
    files:
      - ./resources/Caddyfile
generatorOptions:
  disableNameSuffixHash: true
