---
# yaml-language-server: $schema=https://schemas.rzegocki.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hister
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: hister-secret
    template:
      data:
        HISTER__APP__ACCESS_TOKEN: "{{ .HISTER__APP__ACCESS_TOKEN }}"
  dataFrom:
    - extract:
        key: kubernetes/default/hister
