---
# yaml-language-server: $schema=https://schemas.rzegocki.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nitter
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: nitter-secret
    template:
      data:
        sessions.jsonl: >-
          {"kind": "cookie",
          "auth_token": "{{ .TWITTER_AUTH_TOKEN }}",
          "ct0": "{{ .TWITTER_CT0 }}",
          "username": "{{ .TWITTER_USERNAME }}",
          "id": "{{ .TWITTER_ID }}"}
        nitter.conf: |-
          [Server]
          hostname = "nitter.${ROOT_DOMAIN}"
          title = "nitter"
          address = "0.0.0.0"
          port = 8080
          https = true
          httpMaxConnections = 100
          staticDir = "./public"

          [Cache]
          listMinutes = 240
          rssMinutes = 10
          redisHost = "nitter-dragonfly"
          redisPort = 6379
          redisPassword = ""
          redisConnections = 20
          redisMaxConnections = 30

          [Config]
          hmacKey = "{{ .HMAC_KEY }}"
          base64Media = true
          enableRSS = true
          enableRSSUserTweets = true
          enableRSSUserReplies = true
          enableRSSUserMedia = true
          enableRSSUserArticles = true
          enableRSSSearch = true
          enableRSSList = true
          enableDebug = false
          proxy = ""
          proxyAuth = ""
          apiProxy = ""
          disableTid = false
          maxConcurrentReqs = 2
          maxRetries = 1
          retryDelayMs = 150

          [Preferences]
          theme = "Nitter"
          replaceTwitter = "nitter.${ROOT_DOMAIN}"
          #replaceYouTube = ""
          replaceReddit = "redlib.${ROOT_DOMAIN}"
          proxyVideos = true
          hlsPlayback = false
          infiniteScroll = false
  dataFrom:
    - extract:
        key: kubernetes/default/nitter
