---
# yaml-language-server: $schema=https://schemas.rzegocki.dev/other/app-template-hr.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nitter
spec:
  chartRef:
    kind: OCIRepository
    name: nitter
  interval: 1h
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
          glance/name: nitter
          glance/icon: di:nitter
          glance/url: https://nitter.${ROOT_DOMAIN}
        containers:
          app:
            image:
              repository: zedeus/nitter
              tag: latest@sha256:8ca440fa51d8ce4618d51a6341dabbce784407025e2531343c36e540e0e3c4ba
            env:
              TZ: Europe/Warsaw
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /Jack/status/20
                    port: &port 8080
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 1Gi
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      labels:
        egress.cilium.io/internet: "true"
      securityContext:
        runAsNonRoot: true
        runAsUser: 998
        runAsGroup: 998
        fsGroup: 998
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        ports:
          http:
            port: 80
            targetPort: *port
    route:
      app:
        hostnames:
          - "nitter.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: nitter
                port: 80
            filters:
              - type: ResponseHeaderModifier
                responseHeaderModifier:
                  set:
                    - name: Content-Security-Policy
                      value: >-
                        default-src 'self';
                        img-src 'self' data: blob: https:;
                        media-src 'self' data: blob: https:;
                        object-src 'none';
                        script-src 'self' 'unsafe-inline' 'unsafe-eval';
                        style-src 'self' 'unsafe-inline';
    persistence:
      config:
        type: secret
        name: nitter-secret
        globalMounts:
          - path: /src/nitter.conf
            subPath: nitter.conf
            readOnly: true
      sessions:
        type: secret
        name: nitter-secret
        globalMounts:
          - path: /src/sessions.jsonl
            subPath: sessions.jsonl
            readOnly: true
