---
# yaml-language-server: $schema=https://schemas.ajgon.casa/pocketid.internal/pocketidoidcclient_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: jellyfin
spec:
  launchUrl: https://jellyfin.${ROOT_DOMAIN}
  callbackUrls:
    - "https://jellyfin.${ROOT_DOMAIN}/sso/OID/redirect/pocket-id"
  secret:
    keys:
      clientID: OAUTH_CLIENT_ID
      clientSecret: OAUTH_CLIENT_SECRET
