---
# yaml-language-server: $schema=https://schemas.rzegocki.dev/gateway.envoyproxy.io/httproutefilter_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: HTTPRouteFilter
metadata:
  name: redlib-not-found
spec:
  directResponse:
    statusCode: 404
    contentType: text/plain
    body:
      type: Inline
      inline: "Not Found"
