- name: Home
  columns:
    - size: small
      widgets:
        - type: clock
          hour-format: 24h
          timezones:
            - timezone: UTC
              label: UTC
        - type: rss
          title-url: /rss
          cache: 1h

          limit: 3
          collapse-after: -1
          feeds:
            - $include: secrets/feeds.yaml
        - $include: epic-games.yaml

    - size: full
      widgets:
        - type: hacker-news

        - type: videos
          title: YouTube
          title-url: /youtube
          cache: 1h

          limit: 15
          include-shorts: true # must be true to include livestreams
          channels:
            - $include: secrets/youtube.yaml

    - size: small
      widgets:
        - $include: air-quality.yaml
        - type: weather
          location: Krakow, Poland
          units: metric
          hour-format: 24h
        - type: repository
          repository: deedee-ops/home-ops
          pull-requests-limit: 5
          issues-limit: 3
