- name: Home
  columns:
    - size: small
      widgets:
        - type: clock
          hour-format: 24h
          timezones:
            - timezone: UTC
              label: UTC
        - type: rss
          title-url: /rss
          cache: 1h

          limit: 3
          collapse-after: -1
          feeds:
            - $include: secrets/feeds.yaml
        - $include: epic-games.yaml

    - size: full
      widgets:
        - type: hacker-news

        - type: videos
          title: YouTube
          title-url: /youtube
          cache: 1h

          limit: 15
          include-shorts: true # must be true to include livestreams
          channels:
            - $include: secrets/youtube.yaml

        - type: group
          define: &shared-properties
            type: reddit
            style: vertical-list
            show-thumbnails: true
            comments-url-template: https://redlib.${ROOT_DOMAIN}/{POST-PATH}
          widgets:
            - subreddit: selfhosted
              <<: *shared-properties

            - subreddit: homelab
              <<: *shared-properties

            - subreddit: DataHoarder
              <<: *shared-properties

    - size: small
      widgets:
        - $include: air-quality.yaml
        - type: weather
          location: Krakow, Poland
          units: metric
          hour-format: 24h
        - type: custom-api
          title: Random Fact
          cache: 6h
          url: https://uselessfacts.jsph.pl/api/v2/facts/random
          template: |
            <p class="size-h4 color-paragraph">{{ .JSON.String "text" }}</p>
