- name: k8s
  columns:
    - size: small
      widgets:
        - type: extension
          url: http://localhost:8080/extension/nodes
          allow-potentially-dangerous-html: true
          cache: 1s
    - size: full
      widgets:
        - type: extension
          url: http://localhost:8080/extension/apps
          allow-potentially-dangerous-html: true
          cache: 1s
          parameters:
            # namespace, name annotations
            show-if: |
              "glance/name" in annotations
