- name: YouTube
  slug: youtube
  columns:
    - size: full
      widgets:
        - type: videos
          cache: 1h
          style: grid-cards
          limit: 30
          channels:
            - $include: secrets/youtube.yaml
