---
# yaml-language-server: $schema=https://schemas.ajgon.casa/other/ansible-meta.json
galaxy_info:
  role_name: user
  author: ajgon
  description: Create an unprivileged sudo user and lock sshd down to key based logins
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - user
dependencies: []
