---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: towonel-agent
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: towonel-agent-secret
    template:
      data:
        TOWONEL_INVITE_TOKEN: "{{ .TOWONEL_INVITE_TOKEN }}"
  dataFrom:
    - extract:
        key: kubernetes/network/towonel-agent
