---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: alertmanager-secret
    template:
      data:
        ALERTMANAGER_HEARTBEAT_URL: "{{ .ALERTMANAGER_HEARTBEAT_URL }}"
  dataFrom:
    - extract:
        key: kubernetes/observability/kube-prometheus-stack
---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prometheus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: prometheus-secret
    template:
      data:
        PROMETHEUS_VAULT_TOKEN: "{{ .PROMETHEUS_VAULT_TOKEN }}"
  dataFrom:
    - extract:
        key: kubernetes/observability/kube-prometheus-stack
