---
# yaml-language-server: $schema=https://schemas.ajgon.casa/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: nas-rules
spec:
  groups:
    - name: nas.rules
      rules:
        - alert: NASVMsUnmounted
          expr: >-
            up{node="nas",job="node-exporter"} == 1
            AND on (node) absent(node_filesystem_mount_info{mountpoint="/mnt/fast/vms", node="nas"})
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: NAS /mnt/fast/vms is not mounted.
        - alert: NASTankUnmounted
          expr: >-
            up{node="nas",job="node-exporter"} == 1
            AND on (node) absent(node_filesystem_mount_info{mountpoint="/mnt/tank", node="nas"})
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: NAS /mnt/tank is not mounted.
---
# yaml-language-server: $schema=https://schemas.ajgon.casa/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: openbao-rules
spec:
  groups:
    - name: openbao.rules
      rules:
        - alert: OpenBaoVaultSealed
          expr: vault_core_unsealed == 0
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: OpenBao vault sealed (instance {{ $labels.instance }})
            description: |-
              OpenBao vault instance is sealed on {{ $labels.instance }}
                VALUE = {{ $value }}
                LABELS = {{ $labels }}
