---
# yaml-language-server: $schema=https://schemas.rzegocki.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-operator
spec:
  chartRef:
    kind: OCIRepository
    name: grafana-operator
  interval: 1h
  values:
    annotations:
      glance/name: Grafana
      glance/icon: di:grafana
      glance/url: https://grafana.${ROOT_DOMAIN}
    dashboard:
      enabled: true
    serviceMonitor:
      enabled: true
    podSecurityContext:
      seccompProfile:
        type: RuntimeDefault
    podLabels:
      egress.cilium.io/kube-apiserver: "true"
