---
# yaml-language-server: $schema=https://schemas.ajgon.casa/pocketid.internal/pocketidoidcclient_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: grafana
spec:
  launchUrl: https://grafana.${ROOT_DOMAIN}
  callbackUrls:
    - "https://grafana.${ROOT_DOMAIN}/login/generic_oauth"
  secret:
    keys:
      clientID: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
      clientSecret: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
