---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: glance
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: glance-secret
    template:
      data:
        GLANCE_LATITUDE: "{{ .GLANCE_LATITUDE }}"
        GLANCE_LONGITUDE: "{{ .GLANCE_LONGITUDE }}"
        GLANCE_WAQI_TOKEN: "{{ .GLANCE_WAQI_TOKEN }}"
  dataFrom:
    - extract:
        key: kubernetes/default/glance
---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: glance-config
spec:
  refreshInterval: 10m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: glance-config-secret
    template:
      data:
        feeds.yaml: "{{ .CONFIG_RSS_FEEDS }}"
        youtube.yaml: "{{ .CONFIG_YOUTUBE }}"
  dataFrom:
    - extract:
        key: kubernetes/default/glance
