---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../../../components/namespace
resources:
  - ./_namespace.yaml
  - ./blackbox-exporter.yaml
  - ./gatus.yaml
  - ./grafana.yaml
  - ./keda.yaml
  - ./kromgo.yaml
  - ./kube-prometheus-stack.yaml
  - ./prom-timer.yaml
  - ./silence-operator.yaml
  - ./unpoller.yaml
