---
# yaml-language-server: $schema=https://schemas.ajgon.casa/other/docker-compose.json
#
# IMPORTANT FOR TESTING!
#
# This is UDP-based protocol, so firewall on port 69 needs to be opened on BOTH client and server.
services:
  tftpd:
    environment:
      TFTPD_BIND_ADDRESSi: "0.0.0.0:1069"
      TFTPD_EXTRA_ARGSi: "--blocksize 1468"
    image: registry.gitlab.com/kalaksi-containers/tftpd:1.6@sha256:6205e580af44b1ac37be8a7270259c18cf62ac167487317b70433d98ec50c3a7
    container_name: tftpd
    restart: unless-stopped
    volumes:
      - ${DATA_DOCKER_DIR}/tftpd/data:/tftpboot
    ports:
      - "69:1069/udp"
    # security
    cap_drop:
      - all
    cap_add:
      - CAP_SETGID
      - CAP_SETUID
      - CAP_SYS_CHROOT
    security_opt:
      - no-new-privileges
    read_only: true
