---
# yaml-language-server: $schema=https://schemas.rzegocki.dev/other/docker-compose.json
services:
  kopia-nas:
    environment:
      AWS_ACCESS_KEY_ID: "${KOPIA_NAS_AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${KOPIA_NAS_AWS_SECRET_ACCESS_KEY}"
      KOPIA_PASSWORD: "${KOPIA_PASSWORD}"
      KOPIA_WEB_ENABLED: "false"
      SSL_CERT_FILE: "/etc/ssl/certs/ca-certificates.crt"
      TZ: "Europe/Warsaw"
    image: ghcr.io/home-operations/kopia:0.23.1@sha256:27da0a33b44e1b902150a6c963514237217464bb13118a95bb056667be93cda5
    container_name: kopia-nas-host
    user: "0:0"
    restart: always
    command:
      - server
      - start
      - --insecure
      - --without-password
      - --no-ui
      - --address=127.0.0.1:51515
    configs:
      - source: repository-nas
        target: /config/repository.config
    volumes:
      - /mnt/fast/backups:/mnt/fast/backups:ro
      - /mnt/fast/docker:/mnt/fast/docker:ro
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - ${DATA_DOCKER_DIR}/kopia/nas:/config
    networks:
      - internal
    # security
    cap_drop:
      - all
    cap_add:
      - DAC_READ_SEARCH
    security_opt:
      - no-new-privileges

  kopia-b2:
    environment:
      AWS_ACCESS_KEY_ID: "${KOPIA_B2_AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${KOPIA_B2_AWS_SECRET_ACCESS_KEY}"
      KOPIA_PASSWORD: "${KOPIA_PASSWORD}"
      KOPIA_WEB_ENABLED: "false"
      SSL_CERT_FILE: "/etc/ssl/certs/ca-certificates.crt"
      TZ: "Europe/Warsaw"
    image: ghcr.io/home-operations/kopia:0.23.1@sha256:27da0a33b44e1b902150a6c963514237217464bb13118a95bb056667be93cda5
    container_name: kopia-b2-host
    user: "0:0"
    restart: always
    command:
      - server
      - start
      - --insecure
      - --without-password
      - --no-ui
      - --address=127.0.0.1:51515
    configs:
      - source: repository-b2
        target: /config/repository.config
    volumes:
      - /mnt/fast/backups:/mnt/fast/backups:ro
      - /mnt/fast/docker:/mnt/fast/docker:ro
      - /mnt/tank/documents:/mnt/tank/documents:ro
      - /mnt/tank/photos:/mnt/tank/photos:ro
      - /mnt/tank/private:/mnt/tank/private:ro
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - ${DATA_DOCKER_DIR}/kopia/b2:/config
    networks:
      - internal
    # security
    cap_drop:
      - all
    cap_add:
      - DAC_READ_SEARCH
    security_opt:
      - no-new-privileges

  kopia-b2-monitor:
    environment:
      AWS_ACCESS_KEY_ID: "${KOPIA_B2_AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${KOPIA_B2_AWS_SECRET_ACCESS_KEY}"
      BACKUPS_AT: "20:00"
      BACKUPS_MAX_AGE_HOURS: "12"
      DEEP_AT: "10:30"
      DEEP_DAY_OF_MONTH: "2"
      DEEP_FILES_PERCENT: "100"
      HEALTHCHECKS_URL: "${KOPIA_B2_HEALTHCHECKS_URL}"
      KOPIA_PASSWORD: "${KOPIA_PASSWORD}"
      KOPIA_WEB_ENABLED: "false"
      QUICK_AT: "05:00"
      QUICK_EVERY_DAYS: "3"
      SSL_CERT_FILE: "/etc/ssl/certs/ca-certificates.crt"
      TZ: "Europe/Warsaw"
    image: ghcr.io/home-operations/kopia:0.23.1@sha256:27da0a33b44e1b902150a6c963514237217464bb13118a95bb056667be93cda5
    container_name: kopia-b2-monitor
    entrypoint:
      - "/usr/bin/catatonit"
      - "--"
      - "/bin/bash"
      - "/monitor.sh"
    restart: always
    configs:
      - source: repository-b2-monitor
        target: /config/repository.config
      - source: monitor
        target: /monitor.sh
    volumes:
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - ${DATA_DOCKER_DIR}/kopia/b2-monitor:/config
    networks:
      - internal
    user: "0:0"
    cap_drop:
      - all
    security_opt:
      - no-new-privileges

configs:
  repository-nas:
    file: ./config/repository-nas.config
  repository-b2:
    file: ./config/repository-b2.config
  repository-b2-monitor:
    file: ./config/repository-b2-monitor.config
  monitor:
    file: ./config/monitor.sh

networks:
  internal:
    name: internal
    external: true
