---
# yaml-language-server: $schema=https://schemas.ajgon.casa/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id
spec:
  chartRef:
    kind: OCIRepository
    name: pocket-id
  interval: 1h
  values:
    controllers:
      main:
        type: deployment
        containers:
          app:
            image:
              repository: ghcr.io/pocket-id/pocket-id
              tag: v2.4.0@sha256:3e790c5d4fd82ff276b1c2bc3242be9da13cff204a2b937768ea1eba1e892571
            env:
              ALLOW_USER_SIGNUPS: "disabled"
              ANALYTICS_DISABLED: "true"
              APP_URL: "https://id.${ROOT_DOMAIN}"
              DB_CONNECTION_STRING: /config/pocket-id.db
              EMAILS_VERIFIED: "true"
              EMAIL_LOGIN_NOTIFICATION_ENABLED: "true"
              GEOLITE_DB_PATH: /data/GeoLite2-City.mmdb
              LOG_JSON: "true"
              PORT: &http 80
              SESSION_DURATION: 10080 # 1 week
              SMTP_FROM: "deedee@${ROOT_DOMAIN}"
              SMTP_HOST: "smtp-relay.network.svc.cluster.local"
              SMTP_PORT: "25"
              TRUST_PROXY: "true"
              TZ: "Europe/Warsaw"
              UI_CONFIG_DISABLED: "true"
              UPLOAD_PATH: /data/uploads
              VERSION_CHECK_DISABLED: "true"
            envFrom:
              - secretRef:
                  name: "pocket-id-secret"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - /app/pocket-id
                      - healthcheck
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness: *probes
            resources:
              requests:
                cpu: 25m
                memory: 128Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
          # dummy .well-known for internal routes
          caddy:
            image:
              repository: docker.io/library/caddy
              tag: "2.11.2@sha256:1e40b251ca9639ead7b5cd2cedcc8765adfbabb99450fe23f130eefabf50f4bc"
            args:
              - caddy
              - run
              - --config
              - /config/Caddyfile
            securityContext:
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
                add:
                  - NET_BIND_SERVICE
            resources:
              requests:
                cpu: "5m"
                memory: "128Mi"
              limits:
                cpu: "1000m"
                memory: "512Mi"
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      labels:
        egress.cilium.io/smtp-relay: "true"
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    route:
      main:
        hostnames:
          - "id.${ROOT_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: pocket-id
                port: 80
            filters:
              - type: ResponseHeaderModifier
                responseHeaderModifier:
                  set:
                    - name: Content-Security-Policy
                      value: >-
                        default-src 'self';
                        object-src 'none';
                        script-src 'self' 'unsafe-inline' 'unsafe-eval';
                        style-src 'self' 'unsafe-inline';
              - cors:
                  allowOrigins:
                    - 'https://*.${ROOT_DOMAIN}'
                  allowHeaders:
                    - '*'
                  allowMethods:
                    - '*'
                type: CORS
    service:
      main:
        ports:
          http:
            port: *http
          internal:
            port: 8080
    configMaps:
      caddy:
        enabled: true
        data:
          # yamllint disable rule:line-length
          Caddyfile: |
            {
              log {
                level info
                output stderr
                format console
              }
              http_port 8080
            }
            pocket-id.{{ .Release.Namespace }}.svc.cluster.local:8080 {
              log
              header -Server
              header -X-Powered-By
              encode zstd gzip
              handle /.well-known/openid-configuration {
                header Content-Type "application/json"
                respond <<EOF
                  {
                    "authorization_endpoint": "https://id.${ROOT_DOMAIN}/authorize",
                    "authorization_response_iss_parameter_supported": true,
                    "claims_supported": [
                      "sub",
                      "given_name",
                      "family_name",
                      "name",
                      "email",
                      "email_verified",
                      "preferred_username",
                      "picture",
                      "groups"
                    ],
                    "code_challenge_methods_supported": [
                      "plain",
                      "S256"
                    ],
                    "device_authorization_endpoint": "https://id.${ROOT_DOMAIN}/api/oidc/device/authorize",
                    "end_session_endpoint": "https://id.${ROOT_DOMAIN}/api/oidc/end-session",
                    "grant_types_supported": [
                      "authorization_code",
                      "refresh_token",
                      "urn:ietf:params:oauth:grant-type:device_code",
                      "client_credentials"
                    ],
                    "id_token_signing_alg_values_supported": [
                      "RS256"
                    ],
                    "introspection_endpoint": "http://pocket-id.{{ .Release.Namespace }}.svc.cluster.local/api/oidc/introspect",
                    "issuer": "https://id.${ROOT_DOMAIN}",
                    "jwks_uri": "http://pocket-id.{{ .Release.Namespace }}.svc.cluster.local/.well-known/jwks.json",
                    "response_types_supported": [
                      "code",
                      "id_token"
                    ],
                    "scopes_supported": [
                      "openid",
                      "profile",
                      "email",
                      "groups"
                    ],
                    "subject_types_supported": [
                      "public"
                    ],
                    "token_endpoint": "http://pocket-id.{{ .Release.Namespace }}.svc.cluster.local/api/oidc/token",
                    "userinfo_endpoint": "http://pocket-id.{{ .Release.Namespace }}.svc.cluster.local/api/oidc/userinfo"
                  }
                  EOF 200
              }
            }
          # yamllint enable rule:line-length
    persistence:
      caddy:
        type: configMap
        identifier: caddy
        advancedMounts:
          main:
            caddy:
              - subPath: Caddyfile
                path: /config/Caddyfile
      config:
        existingClaim: pocket-id
        globalMounts:
          - path: /config
            subPath: config
          - path: /data
            subPath: data
