---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oxicloud-db-store
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: oxicloud-db-store-secret
    template:
      data:
        ACCESS_KEY_ID: "{{ .OXICLOUD_DB_ACCESS_KEY_ID }}"
        ACCESS_SECRET_KEY: "{{ .OXICLOUD_DB_ACCESS_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: kubernetes
