---
# yaml-language-server: $schema=https://schemas.rzegocki.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mindwtr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: mindwtr-secret
    template:
      data:
        MINDWTR_CLOUD_AUTH_TOKENS: "{{ .MINDWTR_CLOUD_AUTH_TOKENS }}"
  dataFrom:
    - extract:
        key: kubernetes/default/mindwtr
