---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fix-tweet-bot
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: fix-tweet-bot-secret
    template:
      data:
        DATABASE_NAME: "{{ .FIXTWEETBOT_DATABASE_NAME }}"
        DATABASE_USER: "{{ .FIXTWEETBOT_DATABASE_USER }}"
        DATABASE_PASSWORD: "{{ .FIXTWEETBOT_DATABASE_PASSWORD }}"
        DATABASE_ROOT_PASSWORD: "{{ .FIXTWEETBOT_DATABASE_ROOT_PASSWORD }}"
        DISCORD_TOKEN: "{{ .FIXTWEETBOT_DISCORD_TOKEN }}"
  dataFrom:
    - extract:
        key: kubernetes
